baseURL: https://hellodun.com
title: Duncan Gatuthu
paginate: 6
theme: charlolamode

menu:
  main:
    - name: About
      url: about/
      weight: 30

params:
  author: Duncan Gatuthu
  description: Hello, I'm Duncan Gatuthu. I'm a System and Azure cloud admin. I write about Linux, DevOps, Software Development and tech that I'm using and learning.

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  profileMode:
    enabled: true
    title: Duncan Gatuthu 👋🏽
    description: Profile
    imageUrl: "/images/profile.jpg"
    imageTitle: Duncan Gatuthu
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Check out my blog
        url: https://blog.hellodun.com
  mainSections:
    - articles

  socialIcons:
    - name: github
      url: "https://github.com/hellodun"
    - name: youtube
      url: "https://youtube.com/@hellodun"
    - name: twitter
      url: "https://twitter.com/_hellodun"
    - name: linkedin
      url: "https://www.linkedin.com/in/duncan-gatuthu/"

  # change favicon in images folder (icon for web tab)
  assets:
    favicon: "/images/favicon.ico"
    favicon16x16: "/images/favicon-16.png"
    favicon32x32: "/images/favicon-32.png"
    apple_touch_icon: "/images/apple-touch-icon.png"
    safari_pinned_tab: "/images/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
